sudo: required
services:
  - docker

before_install:
  - docker build -t aravindchandran/docker-react -f Dockerfile.dev .

script:
  - docker run aravindchandran/docker-react npm run test -- -- coverage
